
package it.telecomitalia.pssc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PSSCOrderEntryServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PSSCOrderEntryServiceSoap {


    /**
     * 
     * @param timeStamp
     * @param operationType
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PSSCOrderEntryRequest", action = "http://tempuri.org/PSSCOrderEntryRequest")
    @WebResult(name = "PSSCOrderEntryRequestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PSSCOrderEntryRequest", targetNamespace = "http://tempuri.org/", className = "it.telecomitalia.pssc.PSSCOrderEntryRequest")
    @ResponseWrapper(localName = "PSSCOrderEntryRequestResponse", targetNamespace = "http://tempuri.org/", className = "it.telecomitalia.pssc.PSSCOrderEntryRequestResponse")
    public String psscOrderEntryRequest(
        @WebParam(name = "OperationType", targetNamespace = "http://tempuri.org/")
        String operationType,
        @WebParam(name = "Payload", targetNamespace = "http://tempuri.org/")
        String payload,
        @WebParam(name = "TimeStamp", targetNamespace = "http://tempuri.org/")
        String timeStamp);

}
