package it.matrix.services.userpersonaldata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_02-b08-fcs Generated source version: 2.0
 */
@WebServiceClient(name = "user-personaldata-service", targetNamespace = "urn:aa.rossoalice.alice.it", wsdlLocation = "http://aa.rossoalice.alice.it/aa/services/user-personaldata-service?wsdl")
public class UserPersonaldataService extends Service
{

    private final static URL USERPERSONALDATASERVICE_WSDL_LOCATION;

    static
    {
        URL url = null;
        try
        {
            url = new URL("http://aa.rossoalice.alice.it/aa/services/user-personaldata-service?wsdl");
        }
        catch (MalformedURLException e)
        {
            e.printStackTrace();
        }
        USERPERSONALDATASERVICE_WSDL_LOCATION = url;
    }

    public UserPersonaldataService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public UserPersonaldataService()
    {
        super(USERPERSONALDATASERVICE_WSDL_LOCATION, new QName("urn:aa.rossoalice.alice.it", "user-personaldata-service"));
    }

    /**
     * @return returns UserPersonaldataServicePortType
     */
    @WebEndpoint(name = "user-personaldata-serviceHttpPort")
    public UserPersonaldataServicePortType getUserPersonaldataServiceHttpPort()
    {
        return (UserPersonaldataServicePortType) super.getPort(new QName("urn:aa.rossoalice.alice.it", "user-personaldata-serviceHttpPort"), UserPersonaldataServicePortType.class);
    }

}
