
package it.matrix.services.userprivacydata;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserDP", targetNamespace = "http://services.backoffice.matrix.it/")
public interface UserDP {


    /**
     * 
     * @param phone
     * @param extUserId
     * @param intUserId
     * @param phoneType
     * @param channel
     * @return
     *     returns it.matrix.services.userprivacydata.PhoneResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserPhone", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.ModifyUserPhone")
    @ResponseWrapper(localName = "modifyUserPhoneResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.ModifyUserPhoneResponse")
    public PhoneResponse modifyUserPhone(
        @WebParam(name = "channel", targetNamespace = "")
        String channel,
        @WebParam(name = "int_userId", targetNamespace = "")
        int intUserId,
        @WebParam(name = "ext_userId", targetNamespace = "")
        String extUserId,
        @WebParam(name = "phone_type", targetNamespace = "")
        String phoneType,
        @WebParam(name = "phone", targetNamespace = "")
        String phone);

    /**
     * 
     * @param emailType
     * @param extUserId
     * @param intUserId
     * @param email
     * @param channel
     * @return
     *     returns it.matrix.services.userprivacydata.EmailResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserEmail", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.ModifyUserEmail")
    @ResponseWrapper(localName = "modifyUserEmailResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.ModifyUserEmailResponse")
    public EmailResponse modifyUserEmail(
        @WebParam(name = "channel", targetNamespace = "")
        String channel,
        @WebParam(name = "int_userId", targetNamespace = "")
        int intUserId,
        @WebParam(name = "ext_userId", targetNamespace = "")
        String extUserId,
        @WebParam(name = "email_type", targetNamespace = "")
        String emailType,
        @WebParam(name = "email", targetNamespace = "")
        String email);

    /**
     * 
     * @param channelId
     * @param user
     * @return
     *     returns it.matrix.services.userprivacydata.UserPDP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertUser", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.InsertUser")
    @ResponseWrapper(localName = "insertUserResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.InsertUserResponse")
    public UserPDP insertUser(
        @WebParam(name = "user", targetNamespace = "")
        UserPDP user,
        @WebParam(name = "channel_id", targetNamespace = "")
        String channelId);

    /**
     * 
     * @param intUserid
     * @param emailType
     * @param phoneType
     * @param channelId
     * @return
     *     returns it.matrix.services.userprivacydata.UserPDP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadUserByIntID", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadUserByIntID")
    @ResponseWrapper(localName = "loadUserByIntIDResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadUserByIntIDResponse")
    public UserPDP loadUserByIntID(
        @WebParam(name = "int_userid", targetNamespace = "")
        int intUserid,
        @WebParam(name = "channel_id", targetNamespace = "")
        String channelId,
        @WebParam(name = "email_type", targetNamespace = "")
        List<String> emailType,
        @WebParam(name = "phone_type", targetNamespace = "")
        List<String> phoneType);

    /**
     * 
     * @param emailType
     * @param phoneType
     * @param channelId
     * @param extUserid
     * @return
     *     returns it.matrix.services.userprivacydata.UserPDP
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadUserByExtID", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadUserByExtID")
    @ResponseWrapper(localName = "loadUserByExtIDResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadUserByExtIDResponse")
    public UserPDP loadUserByExtID(
        @WebParam(name = "ext_userid", targetNamespace = "")
        String extUserid,
        @WebParam(name = "channel_id", targetNamespace = "")
        String channelId,
        @WebParam(name = "email_type", targetNamespace = "")
        List<String> emailType,
        @WebParam(name = "phone_type", targetNamespace = "")
        List<String> phoneType);

    /**
     * 
     * @param intUserid
     * @param emailType
     * @param channelId
     * @return
     *     returns it.matrix.services.userprivacydata.EmailResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadEmailFromIntID", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadEmailFromIntID")
    @ResponseWrapper(localName = "loadEmailFromIntIDResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadEmailFromIntIDResponse")
    public EmailResponse loadEmailFromIntID(
        @WebParam(name = "int_userid", targetNamespace = "")
        int intUserid,
        @WebParam(name = "channel_id", targetNamespace = "")
        String channelId,
        @WebParam(name = "email_type", targetNamespace = "")
        List<String> emailType);

    /**
     * 
     * @param intUserid
     * @param phoneType
     * @param channelId
     * @return
     *     returns it.matrix.services.userprivacydata.PhoneResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loadPhoneFromID", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadPhoneFromID")
    @ResponseWrapper(localName = "loadPhoneFromIDResponse", targetNamespace = "http://services.backoffice.matrix.it/", className = "it.matrix.services.userprivacydata.LoadPhoneFromIDResponse")
    public PhoneResponse loadPhoneFromID(
        @WebParam(name = "int_userid", targetNamespace = "")
        int intUserid,
        @WebParam(name = "channel_id", targetNamespace = "")
        String channelId,
        @WebParam(name = "phone_type", targetNamespace = "")
        List<String> phoneType);

}
