
package it.matrix.services.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "user-servicePortType", targetNamespace = "urn:aa.rossoalice.alice.it")
public interface UserServicePortType {


    /**
     * 
     * @param spc
     * @return
     *     returns it.matrix.services.user.UserDetail
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "getUserDataFromSpc", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.user.GetUserDataFromSpc")
    @ResponseWrapper(localName = "getUserDataFromSpcResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.user.GetUserDataFromSpcResponse")
    public UserDetail getUserDataFromSpc(
        @WebParam(name = "spc", targetNamespace = "urn:aa.rossoalice.alice.it")
        String spc)
        throws UserNotFoundException_Exception
    ;

}
