package it.matrix.services.userprofiledata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI. JAX-WS RI 2.0_02-b08-fcs Generated source version: 2.0
 */
@WebServiceClient(name = "user-profiledata-service", targetNamespace = "urn:aa.rossoalice.alice.it", wsdlLocation = "http://aa.rossoalice.alice.it/aa/services/user-profiledata-service?wsdl")
public class UserProfiledataService extends Service
{

    private final static URL USERPROFILEDATASERVICE_WSDL_LOCATION;

    static
    {
        URL url = null;
        try
        {
            url = new URL("http://aa.rossoalice.alice.it/aa/services/user-profiledata-service?wsdl");
        }
        catch (MalformedURLException e)
        {
            e.printStackTrace();
        }
        USERPROFILEDATASERVICE_WSDL_LOCATION = url;
    }

    public UserProfiledataService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    public UserProfiledataService()
    {
        super(USERPROFILEDATASERVICE_WSDL_LOCATION, new QName("urn:aa.rossoalice.alice.it", "user-profiledata-service"));
    }

    public UserProfiledataService(URL wsdlLocation)
    {
        this(wsdlLocation, new QName("urn:aa.rossoalice.alice.it", "user-profiledata-service"));
    }

    /**
     * @return returns UserProfiledataServicePortType
     */
    @WebEndpoint(name = "user-profiledata-serviceHttpPort")
    public UserProfiledataServicePortType getUserProfiledataServiceHttpPort()
    {
        return (UserProfiledataServicePortType) super.getPort(new QName("urn:aa.rossoalice.alice.it", "user-profiledata-serviceHttpPort"), UserProfiledataServicePortType.class);
    }

}
