
package it.matrix.services.userprofiledata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "user-profiledata-servicePortType", targetNamespace = "urn:aa.rossoalice.alice.it")
public interface UserProfiledataServicePortType {


    /**
     * 
     * @param spc
     * @return
     *     returns boolean
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "isAliceHomeTvUserFromSpc", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.IsAliceHomeTvUserFromSpc")
    @ResponseWrapper(localName = "isAliceHomeTvUserFromSpcResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.IsAliceHomeTvUserFromSpcResponse")
    public boolean isAliceHomeTvUserFromSpc(
        @WebParam(name = "spc", targetNamespace = "urn:aa.rossoalice.alice.it")
        String spc)
        throws UserNotFoundException_Exception
    ;

    /**
     * 
     * @param spc
     * @return
     *     returns java.lang.Long
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "getApcFromSpc", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetApcFromSpc")
    @ResponseWrapper(localName = "getApcFromSpcResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetApcFromSpcResponse")
    public Long getApcFromSpc(
        @WebParam(name = "spc", targetNamespace = "urn:aa.rossoalice.alice.it")
        String spc)
        throws UserNotFoundException_Exception
    ;

    /**
     * 
     * @param apc
     * @return
     *     returns java.lang.String
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "getSpcFromApc", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetSpcFromApc")
    @ResponseWrapper(localName = "getSpcFromApcResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetSpcFromApcResponse")
    public String getSpcFromApc(
        @WebParam(name = "apc", targetNamespace = "urn:aa.rossoalice.alice.it")
        Long apc)
        throws UserNotFoundException_Exception
    ;

    /**
     * 
     * @param spc
     * @return
     *     returns it.matrix.services.userprofiledata.UserProfileData
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "getUserFromSpc", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetUserFromSpc")
    @ResponseWrapper(localName = "getUserFromSpcResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetUserFromSpcResponse")
    public UserProfileData getUserFromSpc(
        @WebParam(name = "spc", targetNamespace = "urn:aa.rossoalice.alice.it")
        String spc)
        throws UserNotFoundException_Exception
    ;

    /**
     * 
     * @param cli
     * @return
     *     returns it.matrix.services.userprofiledata.UserProfileData
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "getUserFromCli", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetUserFromCli")
    @ResponseWrapper(localName = "getUserFromCliResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetUserFromCliResponse")
    public UserProfileData getUserFromCli(
        @WebParam(name = "cli", targetNamespace = "urn:aa.rossoalice.alice.it")
        String cli)
        throws UserNotFoundException_Exception
    ;

    /**
     * 
     * @param apc
     * @return
     *     returns it.matrix.services.userprofiledata.UserProfileData
     * @throws UserNotFoundException_Exception
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "urn:aa.rossoalice.alice.it")
    @RequestWrapper(localName = "getUserFromApc", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetUserFromApc")
    @ResponseWrapper(localName = "getUserFromApcResponse", targetNamespace = "urn:aa.rossoalice.alice.it", className = "it.matrix.services.userprofiledata.GetUserFromApcResponse")
    public UserProfileData getUserFromApc(
        @WebParam(name = "apc", targetNamespace = "urn:aa.rossoalice.alice.it")
        Long apc)
        throws UserNotFoundException_Exception
    ;

}
